### ISSUE TITLE
Breaking Change in requestedAllocationList of Order Placement v2.2

### ISSUE THREAD

**Issue by birdflyer-lszo** [swissfintechinnovations/ca-wealth#21]
Hi,

In Order Placement v2.0.x the `accounts` property of  the `requestedAllocation` is an array type (see https://github.com/swissfintechinnovations/ca-wealth/blob/main/OrderPlacement.yaml#L354 and https://github.com/swissfintechinnovations/ca-wealth/blob/main/OrderPlacement.yaml#L304) where in version 2.2 it has become a single object (see https://github.com/swissfintechinnovations/ca-wealth/blob/Update-order-placement-api-to-2.2.0/OrderPlacement.yaml#L660). The name `accounts` of the property still implies plural.

This introduces a breaking change making calls that were working in version 2.0 incompatible with version 2.2. Is that an intentional change? I was a bit surprised to see breaking changes with a minor version.

Thanks for clarification
--Bruno Ritz (ZKB)

**Comment by TLusti** [comment]
Hi Bruno

Thank you for raising this issue.

This breaking change was not introduced intentionally. The intention was, and still is, that the `accounts` property of the `requestedAllocation` is an array type, as the property implies. 

This will be fixed before this version is released.
Best
Thomas

**Comment by birdflyer-lszo** [comment]
Hi Thomas,

thanks a lot for your quick response. I will therefore (at least as an intermediate fix) manually restore the array type so I can continue with the development and then use the fixed version once it has been released.

Cheers
--bruno

**Comment by andiahlm** [comment]
Added fix of the cardinality issue here:
https://github.com/swissfintechinnovations/ca-wealth/pull/17/commits/bd9149c9b5e3d9e3a86fa31c863a6b9a96e0af4c

**Comment by TLusti** [comment]
Has been fixed with Version 2.2.1
